sonar.projectKey=bumblebeee3_GRUPO09-2025-PROYINF
sonar.organization=bumblebeee3

# Nombre
sonar.projectName=GRUPO09-2025-PROYINF
sonar.projectVersion=1.0

# Analizar código del frontend y backend
sonar.sources=.

# Excluir dependencias, builds y otros
sonar.exclusions=**/node_modules/**, **/dist/**, **/build/**, **/coverage/**

# Encoding
sonar.sourceEncoding=UTF-8