sonar.projectKey=bumblebeee3_GRUPO04-2025-PROYINF
sonar.organization=bumblebeee3

# Nombre que verá tu profesor
sonar.projectName=GRUPO04-2025-PROYINF
sonar.projectVersion=1.0

# Analizar código del frontend y backend
sonar.sources=.

# Excluir dependencias, builds y otros
sonar.exclusions=**/node_modules/**, **/dist/**, **/build/**, **/coverage/**

# Encoding
sonar.sourceEncoding=UTF-8